coverage:
  status:
    project:
      default: false
      main:
        target: 80%
        paths:
          - "src/imitation/"
          - "!src/imitation/envs/examples/"
          - "!src/imitation/scripts/"
      auxiliary:
        target: 0%
        paths:
          - "src/imitation/envs/examples/"
          - "src/imitation/scripts/"
      tests:
        # Should not have dead code in our tests
        target: 100%
        paths:
          - "tests/"
    patch:
      default: false
      main:
        paths:
          - "src/imitation/"
          - "!src/imitation/envs/examples/"
          - "!src/imitation/scripts/"
      auxiliary:
        paths:
          - "src/imitation/envs/examples/"
          - "src/imitation/scripts/"
      tests:
        target: 100%
        paths:
          - "tests/"
